Repository banzaicloud/pipeline, pull requests merged in 2018-06, with the labels that each got.

#540 Delete security group for ELB before cluster delete
  cluster/aws.go
Labels: aws

#639 circle: rm dep install, it is installed by default
  .circleci/config.yml
Labels: build

#637 Update bank-vaults to 0.2.2
  Gopkg.lock
  vendor/github.com/banzaicloud/bank-vaults/auth/tokenstore.go
Labels: auth

#638 openapi: Fix number -> integer issues
  client/README.md
  client/api/openapi.yaml
  client/api_auth.go
  client/docs/AuthApi.md
  client/docs/ClusterProfileAmazonAmazonNodePoolsPool1.md
  client/docs/ClusterProfileAzureAzureNodePoolsPool1.md
  client/docs/ClusterProfileGoogleGoogleNodePoolsPool1.md
  client/docs/GetClusterStatusResponse.md
  client/docs/NodePoolStatusAmazon.md
  client/docs/NodePoolStatusAzure.md
  client/docs/NodePoolStatusGoogle.md
  client/docs/NodePoolsAmazon.md
  client/docs/NodePoolsAzure.md
  client/docs/NodePoolsGoogle.md
  client/docs/UpdateAzurePropertiesAzureNodePoolsPool1.md
  client/docs/UpdateGooglePropertiesNodePoolsPool1.md
  client/docs/UpdateNodePoolsAmazon.md
  client/examples/auth/main.go
  client/model_cluster_profile_amazon_amazon_node_pools_pool1.go
  client/model_cluster_profile_azure_azure_node_pools_pool1.go
  client/model_cluster_profile_google_google_node_pools_pool1.go
  client/model_get_cluster_status_response.go
  client/model_node_pool_status_amazon.go
  client/model_node_pool_status_azure.go
  client/model_node_pool_status_google.go
  client/model_node_pools_amazon.go
  client/model_node_pools_azure.go
  client/model_node_pools_google.go
  client/model_update_azure_properties_azure_node_pools_pool1.go
  client/model_update_google_properties_node_pools_pool1.go
  client/model_update_node_pools_amazon.go
  docs/openapi/pipeline.yaml
Labels: client

#643 Fix allowed/secrets authz in Casbin
  auth/authz.go
Labels: secrets

#644 Update golang to 1.10 and alpine to 3.7
  Dockerfile
Labels: build

#650 Align deregistration SQL query to MySQL (it was MariaDB compatible)
  auth/authn.go
  auth/user.go
Labels: auth

#653 Melt ssh package into secret package
  api/cluster.go
  cluster/aks.go
  cluster/aws.go
  cluster/common.go
  model/cluster.go
  secret/ssh.go
Labels: secrets

#658 Store cluste SSH secrets with special name and tag real name
  model/cluster.go
  secret/ssh.go
Labels: secrets
