Repository banzaicloud/pipeline, pull requests merged in 2018-11, with the labels that each got.

#1295 Update bank-vaults to include tokenstore sigsegv fix
  Gopkg.lock
  Gopkg.toml
Labels: bug, vault

#1320 Use VolumeBindingWaitForFirstConsumer in EKS and ACSK when creating the default StorageClass
  cluster/acsk.go
  cluster/eks.go
  cluster/kubernetes.go
Labels: alibaba, eks

#1339 spotguide: post files in base64 encoding to GitHub API
  spotguide/spotguide.go
Labels: bug, spotguides

#1342 Fix missing client code generation
  .circleci/config.yml
Labels: bug, build, client

#1345 create and use SSH keypair on OKE cluster nodes
  cluster/oke.go
  pkg/providers/oracle/cluster/manager/nodepool.go
  pkg/providers/oracle/model/cluster.go
  pkg/providers/oracle/network/manager.go
Labels: oracle

#1349 Bump Helm version to 2.11 and Kubernetes to 1.11
  Gopkg.lock
  Gopkg.toml
  config/config.toml.example
Labels: helm

#1357 Use specific version of aws-iam-authenticator
  Dockerfile
  Dockerfile.dev
Labels: aws, eks

#1360 Get bucket call fixed to return only one item
  api/bucket.go
  database/migrations/1542019624_objectstore_azure_accesssecret_field.up.sql
Labels: bug, enhancement

#1369 Add correlation_id to audit_events
  database/migrations/1542117526_audit_events_correlation_id_field.down.sql
  database/migrations/1542117526_audit_events_correlation_id_field.up.1.sql
  internal/audit/middleware.go
  internal/audit/model_audit_event.go
Labels: audit

#1373 Fix CircleCI test report collection
  .circleci/config.yml
  Makefile
Labels: CircleCI

#1374 Add source spotguide repo name to spotguide repos in Drone
  Gopkg.lock
  spotguide/spotguide.go
Labels: spotguides

#1384 Refactor ASG instance fulfillment wait
  cluster/eks.go
  pkg/cluster/eks/action/actions.go
  pkg/cluster/eks/action/asg_action.go
  pkg/providers/amazon/ec2/spotrequest.go
Labels: eks

#1382 Refactor authorization middleware
  auth/authz.go
  cmd/pipeline/main.go
  internal/auth/middleware.go
  internal/auth/middleware_test.go
Labels: auth

#1395 Fix empty ingress disk size
  cluster/hooks.go
Labels: bug

#1404 Support for latent spotguide repos
  client/SHA256SUMS
  client/api/openapi.yaml
  client/docs/LaunchSpotguidesRequest.md
  client/model_launch_spotguides_request.go
  docs/openapi/pipeline.yaml
  spotguide/spotguide.go
Labels: spotguides

#1420 Fix SpotguideSource
  spotguide/spotguide.go
Labels: spotguides

#1440 Persistent local Vault in docker-compose - just like MySQL
  .circleci/config.yml
  docker-compose.override.yml.dist
  docker-compose.yml
  scripts/vault.hcl
Labels: vault

#1444 Backport spotguide repo
  api/spotguide.go
  auth/events.go
  auth/user.go
  spotguide/spotguide.go
Labels: spotguides

#1419 Spotguide pre-pipeline.yaml templating
  spotguide/spotguide.go
  spotguide/spotguide_test.go
Labels: spotguides
