Repository banzaicloud/pipeline, pull requests merged in 2018-09, with the labels that each got.

#985 Fix GitHub repository creation if the organization is the user
  spotguide/spotguide.go
Labels: spotguides

#987 Spotguide secret generation
  secret/random.go
  secret/store.go
  spotguide/spotguide.go
Labels: spotguides

#982 CICD descriptor structs
  Gopkg.lock
  Gopkg.toml
  spotguide/dronerepoconfig.go
  spotguide/dronerepoconfig_test.go
  spotguide/spotguide.go
Labels: spotguides

#990 Add the whole content of the source repo to the new spotguide repo
  spotguide/spotguide.go
Labels: spotguides

#998 Deployment API: add support for chart packages
  api/helm.go
  client/api/openapi.yaml
  client/docs/CreateUpdateDeploymentRequest.md
  client/model_create_update_deployment_request.go
  cluster/autoscale.go
  cluster/hooks.go
  docs/openapi/pipeline.yaml
  helm/helm.go
  pkg/helm/helm.go
Labels: helm, spotguides

#1001 Add spotguide content after CICD enablement so it triggers a run
  spotguide/spotguide.go
Labels: spotguides

#1017 Merge InstallSecrets with InstallOrUpdateSecrets calls
  cluster/hooks.go
  cluster/secrets.go
  secret/restricted_store.go
Labels: secrets

#1019 Align InstallSecretsRequest's tags
  client/api/openapi.yaml
  client/docs/InstallSecretsRequestQuery.md
  client/model_install_secrets_request_query.go
  client/model_launch_spotguides_request.go
  docs/openapi/pipeline.yaml
Labels: openapi

#1020 Simplify installing secrets to clusters by ID
  client/api/openapi.yaml
  client/docs/InstallSecretsRequestQuery.md
  client/model_install_secrets_request_query.go
  cluster/hooks.go
  cluster/secrets.go
  docs/openapi/pipeline.yaml
  pkg/secret/secret.go
  secret/store.go
Labels: secrets

#1024 Use the same YAML lib as Drone to handle Vargs semantics in pipeline.yaml
  spotguide/dronerepoconfig.go
  spotguide/spotguide.go
Labels: spotguides

#1039 Don't exclude client go files
  .dockerignore
Labels: build

#1038 Add supported flag to deployment listings
  api/helm.go
  client/api/openapi.yaml
  client/docs/ListDeploymentsResponseInner.md
  client/model_list_deployments_response_inner.go
  docs/openapi/pipeline.yaml
  pkg/helm/helm.go
Labels: helm

#1042 spotguide: fix Question struct, fix spotguide.yaml format in DB
  spotguide/spotguide.go
Labels: spotguides

#1054 Spotguide versions
  api/spotguide.go
  client/api/openapi.yaml
  client/docs/LaunchSpotguidesRequest.md
  client/model_launch_spotguides_request.go
  docs/openapi/pipeline.yaml
  spotguide/spotguide.go
Labels: spotguides

#1061 Get email from GitHub (in any case) during registration
  auth/github.go
Labels: auth, github

#1064 Fix missing version in spotguide.LaunchRequest
  spotguide/spotguide.go
Labels: spotguides

#1065 Mark spotguide repos in CI/CD
  Gopkg.lock
  Gopkg.toml
  spotguide/spotguide.go
Labels: cicd, spotguides

#1079 DRONE_REPO_CONFIG in docker-compose.yml
  docker-compose.yml
Labels: spotguides

#1057 Security scan OpenApi3 definition
  client/README.md
  client/api/openapi.yaml
  client/api_policies.go
  client/api_scanlog.go
  client/api_whitelist.go
  client/client.go
  client/docs/ImageContent.md
  client/docs/ImageDetail.md
  client/docs/ImageRef.md
  client/docs/ImageSelectionRule.md
  client/docs/MappingRule.md
  client/docs/PoliciesApi.md
  client/docs/Policy.md
  client/docs/PolicyBundle.md
  client/docs/PolicyBundleList.md
  client/docs/PolicyBundleRecord.md
  client/docs/PolicyRule.md
  client/docs/PolicyRuleParams.md
  client/docs/ReleaseWhiteList.md
  client/docs/ReleaseWhiteListItem.md
  client/docs/ScanLogItem.md
  client/docs/ScanLogList.md
  client/docs/ScanlogApi.md
  client/docs/Whitelist.md
  client/docs/WhitelistApi.md
  client/docs/WhitelistItem.md
  client/model_image_content.go
  client/model_image_detail.go
  client/model_image_ref.go
  client/model_image_selection_rule.go
  client/model_mapping_rule.go
  client/model_policy.go
  client/model_policy_bundle.go
  client/model_policy_bundle_list.go
  client/model_policy_bundle_record.go
  client/model_policy_rule.go
  client/model_policy_rule_params.go
  client/model_release_white_list.go
  client/model_release_white_list_item.go
  client/model_scan_log_item.go
  client/model_scan_log_list.go
  client/model_whitelist.go
  client/model_whitelist_item.go
  docs/openapi/pipeline.yaml
Labels: security-scan

#1083 audit: validate JSON before saving to DB
  internal/audit/middleware.go
Labels: audit

#1100 Update auth lib (http scheme detection fix)
  Gopkg.lock
Labels: auth

#1101 secretName support
  api/bucket.go
  api/bucket_messages.go
  api/cluster_create.go
  client/api/openapi.yaml
  client/docs/CreateClusterRequest.md
  client/docs/CreateObjectStoreBucketRequest.md
  client/docs/LoggingPostHookInstallLogging.md
  client/model_create_cluster_request.go
  client/model_create_object_store_bucket_request.go
  client/model_logging_post_hook_install_logging.go
  cluster/hooks.go
  docs/openapi/pipeline.yaml
  pkg/cluster/base.go
Labels: secrets

#1107 Support spotguide version/tag move when scraping
  spotguide/spotguide.go
Labels: spotguides
