Repository banzaicloud/pipeline, pull requests merged in 2018-10, with the labels that each got.

#1118 Preserve pipeline.yaml's pipeline order
  spotguide/dronerepoconfig.go
  spotguide/spotguide.go
Labels: spotguides

#1124 Support private spotguide user repos
  spotguide/spotguide.go
Labels: spotguides

#1122 Add AWS Authenticator to dev docs
  docs/developer.md
Labels: auth, aws

#1134 Fix GKE select
  cluster/gke.go
Labels: google

#1142 Add secretName support to BucketStatusRequest
  api/bucket.go
  client/api/openapi.yaml
  client/api_storage.go
  client/docs/StorageApi.md
  docs/openapi/pipeline.yaml
Labels: secrets

#1150 Make SyncSpotguides a synchronous call
  api/spotguide.go
Labels: spotguides

#1155 Support the more flexible spotguide questionnaire format
  pkg/helm/helm.go
  spotguide/spotguide.go
  spotguide/spotguide_test.go
Labels: spotguides

#1157 Fix make shell in Dockerfile
  Dockerfile
Labels: build

#1160 Support deleting obsolete spotguides during scraping
  spotguide/spotguide.go
Labels: spotguides

#1171 Clear client directory before generating client code
  Makefile
  client/docs/InstallSecretsResponseItem.md
  client/model_install_secrets_response_item.go
Labels: client

#1183 Fix marshaling issues in spotguide's install secret requests
  Gopkg.lock
  Gopkg.toml
  cluster/secrets.go
  spotguide/dronerepoconfig.go
  spotguide/spotguide.go
Labels: spotguides

#1186 Change HtpasswdFile key on htpasswd secret type
  pkg/secret/secret.go
Labels: secrets

#1191 Spotguide: support all kinds of Pipeline JSON merging + Unit test
  Gopkg.lock
  Gopkg.toml
  spotguide/dronerepoconfig.go
  spotguide/spotguide.go
  spotguide/spotguide_test.go
Labels: spotguides

#1192 Return error in case of unsupported field query value
  api/cluster.go
Labels: bug

#1201 Upgrade Helm to the requested version if installed already
  cluster/hooks.go
  helm/install.go
Labels: helm

#1239 Registration whitelist
  auth/github.go
  auth/migrate.go
  auth/user.go
  config/config.toml.example
  config/configuration.go
  ddl/01_whitelisted_auth_identities.sql
  docs/developer.md
Labels: auth

#1240 Route53 env name
  dns/route53/iamUser.go
  dns/route53/policy.go
  dns/route53/route53.go
  dns/route53/route53_test.go
  pkg/amazon/iamSvc.go
Labels: aws

#1237 EKS: wait for ASGs
  cluster/acsk.go
  cluster/eks.go
  cluster/manager_delete.go
  pkg/cluster/eks/action/actions.go
  pkg/cluster/eks/action/asg_action.go
  pkg/providers/amazon/autoscaling/autoscaling.go
  pkg/providers/amazon/autoscaling/errors.go
  pkg/providers/amazon/autoscaling/instance.go
  pkg/providers/amazon/autoscaling/manager.go
  pkg/providers/amazon/ec2/errors.go
  pkg/providers/amazon/ec2/spotrequest.go
Labels: eks, enhancement

#1250 Fix secret tagging of monitoring and logging
  cluster/hooks.go
  config/configuration.go
Labels: secrets

#1252 Remove redirect from logout
  auth/authn.go
Labels: auth

#1253 Alibaba error details
  cluster/acsk.go
  pkg/cluster/acsk/action/actions.go
  pkg/cluster/acsk/defaults.go
  pkg/cluster/acsk/template.go
Labels: alibaba

#1261 Update GitHub OAuth access token at further logins
  Gopkg.lock
  auth/github.go
  auth/user.go
Labels: auth

#1256 API token as Cookie
  Gopkg.lock
  Gopkg.toml
  api/user.go
  auth/authn.go
  auth/authz.go
  auth/error_handler.go
  auth/user.go
  internal/platform/database/dsn.go
  main.go
  secret/store.go
Labels: auth, vault

#1267 Close Helm clients to prevent port and memory leakage
  cluster/hooks.go
  helm/helm.go
  pkg/helm/client.go
Labels: bug, helm

#1279 Use bank-vaults with CA cert auto reload
  Gopkg.lock
  Gopkg.toml
Labels: vault

#1288 spotguide release tags can be filtered by pre-releases
  Gopkg.toml
  config/config.toml.example
  config/configuration.go
  spotguide/spotguide.go
Labels: spotguides
