Repository banzaicloud/pipeline, pull requests merged in 2018-08, with the labels that each got.

#780 EKS: Parallel nodePool creation and update
  cluster/eks.go
  pkg/cluster/eks/action/actions.go
Labels: aws

#797 Add config to modify cookie domains
  auth/authn.go
  auth/util.go
  config/config.toml.example
Labels: auth

#897 Small Alibaba fixes around RBAC and DeleteCluster()
  cluster/acsk.go
Labels: alibaba

#905 Fix DockerHub build (vendoring)
  Dockerfile
Labels: build

#904 Update Alibaba SDK to fix CS issues
  Gopkg.lock
  Gopkg.toml
  cluster/acsk.go
Labels: alibaba

#911 Initializes nodepool labels (if needed) in case of OKE
  pkg/providers/oracle/cluster/cluster.go
Labels: oracle

#912 Add .pipeline.yml
  .pipeline.yml
Labels: cicd

#916 Add default image to OKE cluster in case of create/update
  pkg/providers/oracle/cluster/cluster.go
  pkg/providers/oracle/cluster/defaults.go
Labels: oracle

#949 spotguide: token and repo scraping fixes
  main.go
  spotguide/spotguide.go
Labels: spotguides
