Repository banzaicloud/pipeline, pull requests merged in 2019-12, with the labels that each got.

#2583 auth/google: group domain -> org, group name -> role
  src/auth/oidc.go
Labels: area/auth, component/dex

#2588 Remove the CreateClusterRoles posthook
  pkg/cluster/base.go
  src/cluster/hookfunctions.go
  src/cluster/hooks.go
Labels: area/auth, platform/pke

#2613 Change Service URL format
  internal/cluster/endpoints/endpoints.go
Labels: area/integrated-services
