Repository banzaicloud/pipeline, pull requests merged in 2019-01, with the labels that each got.

#1578 Update bank-vaults to use Vault client 1.0.x
  Gopkg.lock
  Gopkg.toml
Labels: vault

#1596 Fix create oke cluster example values
  docs/postman/e2e_test.postman_collection.json
Labels: oracle

#1608 Fix org import user association
  auth/user.go
Labels: auth, bug

#1587 Create PR template
  .github/PULL_REQUEST_TEMPLATE.md
  docs/error-handling-guide.md
Labels: DX

#1630 added section about golang-migrate to migration docs
  docs/migrations.md
Labels: DX

#1634 Update yaml library
  Gopkg.lock
  Gopkg.toml
Labels: bug

#1656 Validate custom OKE labels
  pkg/providers/oracle/cluster/cluster.go
  pkg/providers/oracle/model/cluster.go
Labels: oracle

#1663 distribution clusterUID scan fix
  secret/store.go
Labels: distribution, secrets

#1671 Dex based authentication
  .gitignore
  Gopkg.lock
  Gopkg.toml
  Makefile
  api/organization.go
  api/user.go
  auth/authn.go
  auth/github.go
  auth/user.go
  client/README.md
  client/SHA256SUMS
  client/api/openapi.yaml
  client/api_users.go
  client/docs/GetClusterNodePool.md
  client/docs/GetClusterResponse.md
  client/docs/UpdateUserRequest.md
  client/docs/User.md
  client/docs/UsersApi.md
  client/model_get_cluster_node_pool.go
  client/model_get_cluster_response.go
  client/model_update_user_request.go
  client/model_user.go
  cmd/pipeline/main.go
  config/config.toml.example
  config/configuration.go
  config/dex.yml.example
  database/migrations/1547212232_add_org_provider_field.down.sql
  database/migrations/1547212232_add_org_provider_field.up.sql
  docker-compose.anchore.yml.dist
  docker-compose.override.yml.dist
  docker-compose.yml
  docs/github-app.md
  docs/images/howto/OAuthAppReg.png
  docs/openapi/pipeline.yaml
  internal/auth/access.go
  internal/auth/access_test.go
  views/auth/login/providers/dex.tmpl
  views/auth/register/providers/dex.tmpl
Labels: area/auth

#1680 fix dex clientId
  config/dex.yml.example
Labels: area/auth

#1682 update auth/dex dep (holds https redirection fix)
  Gopkg.lock
Labels: area/auth

#1685 Implement revoke github token for user
  api/user.go
  auth/user.go
Labels: area/auth

#1687 docker-compose: restart cicd always, fix image
  docker-compose.yml
Labels: DX, component/cicd
