Repository banzaicloud/pipeline, pull requests merged in 2019-08, with the labels that each got.

#2202 Remove duplicate community files
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_request.md
  .github/SUPPORT.md
  .github/support_issue.png
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: DX

#2203 Fix default banzaicloud stable helm chart URL
  config/config.toml.dist
  config/configuration.go
Labels: component/helm

#2177 spotguide: scrape shared spotguides in cron workflow
  cmd/pipeline/main.go
  cmd/worker/config.go
  cmd/worker/main.go
  config/configuration.go
  spotguide/spotguide.go
  spotguide/sync_spotguides_workflow.go
Labels: area/spotguides, component/cadence

#2237 Fix worker database config
  cmd/worker/config.go
Labels: kind/backport, kind/bug

#2236 Fix worker database config
  cmd/worker/config.go
Labels: kind/bug

#2240 dex: fix ldap filter in sample config
  config/dex.yml.dist
Labels: area/auth, component/dex
