Repository banzaicloud/pipeline, pull requests merged in 2019-02, with the labels that each got.

#1695 spotguide: fix SIGSEGV during scrape if resp is not available
  spotguide/spotguide.go
Labels: area/spotguides, kind/bug

#1701 Configure bypass egress traffic on EKS for Istio posthook
  cluster/eks.go
  cluster/gke.go
  cluster/hooks_istio.go
  pkg/cluster/base.go
Labels: component/istio, platform/eks

#1714 Configure bypass egress traffic on AKS for Istio posthook
  cluster/aks.go
Labels: cloud/azure, component/istio

#1717 remove non-DNS friendly characters from email derived login name
  auth/user.go
  auth/user_test.go
Labels: area/auth

#1721 Allow PATCH method in CORS
  config/configuration.go
Labels: kind/bug

#1732 Configure bypass egress traffic on OKE for Istio posthook
  cluster/oke.go
Labels: cloud/oracle, component/istio

#1738 client: add expiresAt field to TokenCreateRequest
  client/SHA256SUMS
  client/api/openapi.yaml
  client/docs/TokenCreateRequest.md
  client/model_token_create_request.go
  docs/openapi/pipeline.yaml
Labels: area/client

#1733 Configure bypass egress traffic on PKE for Istio posthook
  cluster/dummy.go
  cluster/ec2_pke.go
Labels: area/distribution, component/istio

#1746 update cicd to 0.8.2
  docker-compose.yml
Labels: area/auth, component/cicd

#1753 bump cicd
  docker-compose.yml
Labels: component/cicd

#1761 spotguide: add org name to enable-repo request
  Gopkg.lock
  Gopkg.toml
  api/spotguide.go
  auth/user.go
  docker-compose.yml
  spotguide/spotguide.go
Labels: area/auth, area/spotguides

#1764 remove casbin
  Gopkg.lock
  Gopkg.toml
  README.md
  auth/authn.go
  auth/migrate.go
  cmd/pipeline/main.go
  config/database_casbin.go
  internal/auth/.gitignore
  internal/auth/access.go
  internal/auth/access_test.go
  internal/auth/enforcer.go
  internal/auth/middleware.go
  internal/auth/middleware_test.go
Labels: area/auth

#1776 Run vendor on demand
  Makefile
Labels: DX

#1806 Pke nodepool count
  cluster/ec2_pke.go
  database/migrations/1551273183_add_pke_nodepools_autoscaling.down.sql
  database/migrations/1551273183_add_pke_nodepools_autoscaling.up.sql
  internal/providers/pke/nodepool.go
  internal/providers/pke/nodepool_provider_config_amazon.go
  internal/providers/pke/pkeworkflow/cluster.go
  internal/providers/pke/pkeworkflow/create_aws_worker_pool_activity.go
  internal/providers/pke/pkeworkflow/pkeworkflowadapter/cluster_manager.go
  internal/providers/pke/pkeworkflow/update_aws_pool_activity.go
  pkg/cluster/pke/types.go
  templates/pke/worker.cf.yaml
Labels: area/distribution

#1822 Remove anchore restart from dev environment
  Makefile
  docker-compose.anchore.yml.dist
  docker-compose.override.yml.dist
  docs/developer.md
Labels: DX
