Repository banzaicloud/pipeline, pull requests merged in 2019-09, with the labels that each got.

#2255 secret: change how we decide TLS secret generation
  pkg/secret/secret.go
  secret/store.go
Labels: area/secret

#2260 audit: change JSON binding errors to http 400 and return error as well
  internal/audit/middleware.go
Labels: area/audit

#2265 Relocate pipelinectl app files
  cmd/pipelinectl/main.go
  internal/app/pipelinectl/cli/commands/cmd.go
  internal/app/pipelinectl/cli/commands/drain/cmd.go
  internal/app/pipelinectl/cli/commands/drain/common.go
  internal/app/pipelinectl/cli/commands/drain/disable.go
  internal/app/pipelinectl/cli/commands/drain/enable.go
  internal/app/pipelinectl/cli/commands/drain/status.go
Labels: kind/enhancement, kind/tech-debt

#2286 cicd: make it optional
  api/spotguide.go
  auth/authn.go
  auth/user.go
  cmd/pipeline/main.go
  config/config.toml.dist
  config/configuration.go
Labels: component/cicd

#2289 oidc: handle refresh token in cli login flow
  auth/oidc.go
Labels: component/dex

#2299 spotguides: path fix
  cmd/pipeline/main.go
Labels: area/spotguides

#2305 Minor code improvements
  internal/app/frontend/notification/common.go
  internal/app/frontend/notification/notification.go
  internal/app/frontend/notification/notificationdriver/endpoints_test.go
  internal/app/frontend/notification/notificationdriver/transport_http.go
  internal/app/frontend/notification/notificationdriver/transport_http_test.go
Labels: area/frontend, kind/enhancement

#2314 Upgrade linter
  .golangci.yml
  Makefile
  auth/authadapter/organization_store_test.go
  auth/authn.go
  auth/role.go
  auth/scm.go
  cluster/eks.go
  cluster/ttl_controller_test.go
  pkg/cluster/eks/action/network.go
  pkg/cluster/eks/action/nodepools.go
Labels: DX
