Repository banzaicloud/pipeline, pull requests merged in 2019-05, with the labels that each got.

#1989 Check enable/create backup request location field just in case of Ama…
  api/ark/backupservice/enable.go
  api/ark/buckets/create.go
Labels: kind/bug

#2000 make cicd db name configurable
  config/config.toml.dist
  config/configuration.go
  config/database_cicd.go
  database/docker-init-mysql.sql
  database/docker-init-postgres.sql
  docker-compose.override.yml.dist
  docker-compose.yml
Labels: component/cicd

#2008 docker-compose: bump dex to re-enable password login
  docker-compose.yml
Labels: component/dex

#2043 dex: support for insecure tls
  auth/authn.go
  config/config.toml.dist
  config/configuration.go
  go.mod
  go.sum
Labels: component/dex

#2044 dex: make insecure configurable in ClusterAuthAPI as well
  api/cluster_auth.go
  cmd/pipeline/main.go
Labels: component/dex

#2045 bump auth version to v0.1.3
  go.mod
  go.sum
Labels: area/auth

#2059 spotguide: gitlabTag.Release can be nil, use .Name instead
  spotguide/scm/gitlab.go
Labels: area/spotguides, gitlab

#2061 Filter out Unauthorized response code in case of Amazon specific errors
  api/common_stuff.go
Labels: cloud/aws
