Repository banzaicloud/pipeline, pull requests merged in 2020-03, with the labels that each got.

#2772 Drop TTL fields
  database/migrations/mysql/1583070164_drop_ttl_minutes_column_from_clusters_table.down.sql
  database/migrations/mysql/1583070164_drop_ttl_minutes_column_from_clusters_table.up.sql
  database/migrations/postgres/1583070164_drop_ttl_minutes_column_from_clusters_table.down.sql
  database/migrations/postgres/1583070164_drop_ttl_minutes_column_from_clusters_table.up.sql
  internal/cluster/clusteradapter/gorm_model.go
  src/model/migrate.go
Labels: area/database, kind/tech-debt

#2773 Return 404 when a secret cannot be found
  src/api/secrets.go
Labels: area/secret, kind/bug

#2775 validate cluster befere delete (#2750)
  cmd/pipeline/main.go
  cmd/worker/main.go
  internal/cluster/service.go
  internal/cluster/service_node_pool_test.go
  internal/cluster/zz_generated.mock_test.go
  internal/clustergroup/manager.go
Labels: kind/backport

#2779 Move common gorm code to separate package
  internal/providers/google/model.go
  pkg/gormhelper/migrate.go
  src/model/migrate.go
Labels: kind/tech-debt

#2781 Fix google orm foreign key
  internal/providers/google/model.go
Labels: area/database, kind/tech-debt

#2782 Reorganize models
  cmd/pipeline/migrate.go
  internal/cluster/clusteradapter/clustermodel/cluster.go
  internal/cluster/clusteradapter/clustermodel/cluster_status_history.go
  internal/cluster/clusteradapter/clustermodel/log.go
  internal/cluster/clusteradapter/clustermodel/migrate.go
  internal/cluster/clusteradapter/clustermodel/scale_options.go
  internal/cluster/clusteradapter/gorm_cluster_status_history_model.go
  internal/cluster/clusteradapter/gorm_clusters.go
  internal/cluster/clusteradapter/store.go
  internal/providers/azure/pke/adapter/gorm_store.go
  internal/providers/google/gke_cluster_model.go
  internal/providers/google/gke_cluster_model_test.go
  internal/providers/google/model.go
  internal/providers/pke/ec2_cluster_model.go
  src/cluster/common.go
  src/cluster/ec2_pke.go
  src/cluster/gke.go
  src/cluster/gke_global.go
  src/model/cluster.go
  src/model/migrate.go
Labels: area/database, kind/tech-debt

#2783 Refactor amazon foreign keys
  internal/providers/amazon/amazonadapter/migrate.go
  src/model/migrate.go
Labels: area/database, kind/tech-debt

#2786 Return 404 when a secret cannot be found
  src/api/secrets.go
Labels: area/secret, kind/backport, kind/bug

#2787 Wait for PKE global stack in the right region
  internal/providers/pke/pkeworkflow/create_cluster.go
Labels: area/distribution, kind/bug, platform/pke

#2801 Add ref support to snapshot
  Makefile
Labels: DX

#2804 Fix EKS model save
  internal/cluster/distribution/eks/eksprovider/workflow/save_network_details_activity.go
  internal/cluster/distribution/eks/eksprovider/workflow/save_nodepools_activity.go
Labels: kind/bug

#2822 use run.Group
  cmd/pipeline/main.go
Labels: kind/enhancement

#2826 vsphere: fix openapi case
  .gen/pipeline/pipeline/model_pke_on_vsphere_node_pool.go
  src/api/cluster/pke_vsphere.go
Labels: dev/openapi

#2828 Fix potential panic in anchore client
  internal/security/anchore_client.go
Labels: kind/bug

#2830 make ca cert optional (client auth)
  cmd/pipeline/main.go
Labels: area/auth
