Repository banzaicloud/pipeline, pull requests merged in 2020-02, with the labels that each got.

#2695 Remove unused security scan call
  cmd/pipeline/main.go
  internal/global/config.go
  src/api/security.go
Labels: kind/tech-debt

#2694 Upgrade semver to v3
  go.mod
  go.sum
  internal/cluster/clustersetup/activity_install_tiller_wait.go
  internal/providers/amazon/eks/workflow/bootstrap_activity.go
  internal/providers/amazon/eks/workflow/create_eks_control_plane_activity.go
  internal/providers/pke/pkeworkflow/create_cluster.go
  pkg/cluster/eks/defaults.go
  pkg/cluster/eks/eks.go
  src/cluster/autoscale.go
  src/cluster/gke.go
  src/spotguide/spotguide.go
Labels: kind/tech-debt

#2706 [Monitoring] Enable service monitor in pushgateway
  internal/integratedservices/services/monitoring/operator.go
  internal/integratedservices/services/monitoring/values.go
Labels: area/integrated-services

#2707 eks: make aws-auth ConfigMap future compatible
  internal/providers/amazon/eks/workflow/bootstrap_activity.go
Labels: platform/eks

#2709 tiller: eliminate possible tunnel leaks
  internal/kubernetes/client_factory.go
  pkg/helm/client.go
Labels: kind/bug

#2697 Remove unused endpoints from openapi
  apis/pipeline/pipeline.yaml
Labels: area/integrated-services, kind/tech-debt

#2730 ci: postgres needs explicit grant now
  .circleci/config.yml
Labels: build

#2727 vault-is: fix service account token visibility race-condition
  internal/integratedservices/services/vault/common_test.go
  internal/integratedservices/services/vault/operator.go
Labels: area/integrated-services, kind/bug

#2740 Relocate ssh secret tools
  internal/providers/azure/pke/driver/ssh.go
  internal/secret/sshsecret/ssh.go
Labels: kind/tech-debt

#2741 Fix error handling strategy
  Makefile
  internal/app/frontend/notification/notificationdriver/zz_generated.endpoint.go
  internal/app/pipeline/auth/token/tokendriver/zz_generated.endpoint.go
  internal/app/pipeline/cloud/google/project/projectdriver/zz_generated.endpoint.go
  internal/app/pipeline/secrettype/secrettypedriver/zz_generated.endpoint.go
  internal/cluster/clusterdriver/zz_generated.endpoint.go
  internal/integratedservices/integratedservicesdriver/zz_generated.endpoint.go
Labels: kind/bug

#2736 Store SSH key generation in case of Amazon EKS
  database/migrations/mysql/1545432369_add_eks_vpc_subnet_fields.up.sql
  database/migrations/mysql/1581585238_eks_ssh_generated_field.down.sql
  database/migrations/mysql/1581585238_eks_ssh_generated_field.up.sql
  database/migrations/postgres/1556992560_init.up.sql
  database/migrations/postgres/1581585238_eks_ssh_generated_field.down.sql
  database/migrations/postgres/1581585238_eks_ssh_generated_field.up.sql
  internal/providers/amazon/eks/driver/cluster_creator.go
  internal/providers/amazon/eks/driver/cluster_deleter.go
  internal/providers/amazon/eks/driver/cluster_updater.go
  internal/providers/amazon/eks/workflow/create_infra.go
  internal/providers/amazon/eks/workflow/create_infra_test.go
  internal/providers/amazon/eks/workflow/delete_infra.go
  internal/providers/amazon/eks/workflow/delete_infra_test.go
  src/cluster/eks.go
  src/cluster/eks_create_cluster.go
  src/cluster/eks_delete_cluster.go
  src/cluster/eks_update_cluster.go
  src/model/cluster.go
Labels: platform/eks

#2749 Update run group
  cmd/worker/main.go
  go.mod
  go.sum
Labels: kind/tech-debt

#2761 protoc: use the bin version and use includes
  Makefile
Labels: DX

#2762 Make pke global region configurable
  .golangci.yml
  cmd/worker/aws.go
  cmd/worker/config.go
  cmd/worker/main.go
  config/config.yaml.dist
  internal/cmd/config.go
  internal/providers/pke/pkeworkflow/create_cluster.go
Labels: area/distribution, kind/enhancement, platform/pke
