Repository banzaicloud/pipeline, pull requests merged in 2020-05, with the labels that each got.

#2902 drop spotguide_repos model
  cmd/pipeline/migrate.go
  database/migrations/mysql/1588601076_drop_spotguide_repos_table.down.sql
  database/migrations/mysql/1588601076_drop_spotguide_repos_table.up.sql
  database/migrations/postgres/1588601076_drop_spotguide_repos_table.down.sql
  database/migrations/postgres/1588601076_drop_spotguide_repos_table.up.sql
  src/spotguide/migrate.go
Labels: area/spotguides

#2912 process: write log when finishing process
  internal/app/pipeline/process/processadapter/gorm_store.go
Labels: kind/bug

#2909 Set template name in cluster create and update flows
  internal/providers/vsphere/pke/driver/cluster_creator.go
  internal/providers/vsphere/pke/driver/cluster_updater.go
Labels: area/cluster, provider/vsphere

#2930 Fix Amazon PKE cluster update workflow
  src/api/cluster_update.go
Labels: distribution/pke

#2942 Fix pipelinectl env vars
  charts/pipeline/templates/deployment.yaml
Labels: kind/bug

#2946 add processlog and MaximumAttempts to CalculateNodePoolVersionActivity
  internal/cluster/distribution/eks/eksworkflow/workflow_update_node_pool.go
Labels: area/cluster

#2950 Add helm version compile time
  Makefile
  cmd/pipeline/capabilities.go
  cmd/pipeline/main.go
  go.mod
Labels: kind/tech-debt

#2952 add node pool upgrade options
  .gen/pipeline/api/openapi.yaml
  .gen/pipeline/pipeline/model_base_update_node_pool_options.go
  .gen/pipeline/pipeline/model_eks_update_node_pool_request.go
  .gen/pipeline/pipeline/model_eks_update_node_pool_request_all_of.go
  .gen/pipeline/pipeline/model_update_node_pool_drain_options.go
  .gen/pipeline/pipeline/model_update_node_pool_request.go
  apis/pipeline/pipeline.yaml
  internal/cluster/distribution/eks/eksadapter/node_pool_manager.go
  internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
  internal/cluster/distribution/eks/eksworkflow/workflow_update_node_pool.go
  internal/cluster/distribution/eks/service.go
  templates/eks/amazon-eks-nodepool-cf.yaml
Labels: area/cluster
