Repository banzaicloud/pipeline, pull requests merged in 2021-05, with the labels that each got.

#3493 Upgraded Cadence dev server 0.16.1->0.17.0
  docker-compose.yml
Labels: component/cadence

#3499 Added CI integrity checks
  .github/workflows/ci.yml
Labels: DX

#3502 Fixed CI integrity check
  .github/workflows/ci.yml
Labels: DX

#3509 Fixed CI integrity check
  .github/workflows/ci.yml
Labels: DX

#3487 Upgraded pkg/sdk module Go version to 1.16
  .github/workflows/ci.yml
  pkg/sdk/go.mod
  pkg/sdk/go.sum
Labels: kind/enhancement

#3510 GitHub scan
  .github/workflows/scan-images.yml
  docker.images.list
Labels: kind/enhancement
