Repository banzaicloud/pipeline, pull requests merged in 2021-06, with the labels that each got.

#3517 Upgraded local development Cadence server 0.18.2,web 3.26.0
  docker-compose.yml
Labels: DX, component/cadence, kind/enhancement

#3519 Fixed etcd, kube-apiserver binary sources
  Makefile
Labels: DX

#3518 Upgraded Grype 0.11.0->0.13.0
  Makefile
Labels: DX

#3520 Updated image scan images list
  Makefile
  docker.images.list
Labels: DX

#3521 Updated EKS node pool CloudFormation template
  templates/eks/amazon-eks-nodepool-cf.yaml
Labels: area/node-pool, cloud/aws, distribution/eks, kind/enhancement

#3526 Save K8s config right after EKSCluster create has completed
  internal/cluster/distribution/eks/eksprovider/workflow/create_infra.go
Labels: kind/bug

#3532 Added configuration parameter for EKS node pool volume type
  .gen/pipeline/api/openapi.yaml
  .gen/pipeline/pipeline/model_eks_node_pool_all_of.go
  .gen/pipeline/pipeline/model_eks_update_node_pool_request.go
  .gen/pipeline/pipeline/model_eks_update_node_pool_request_all_of.go
  .gen/pipeline/pipeline/model_node_pool.go
  .gen/pipeline/pipeline/model_node_pool_summary.go
  .gen/pipeline/pipeline/model_update_node_pool_request.go
  apis/pipeline/pipeline.yaml
  internal/cluster/distribution/eks/eksadapter/node_pool_manager.go
  internal/cluster/distribution/eks/eksadapter/node_pool_store.go
  internal/cluster/distribution/eks/ekscluster/eks.go
  internal/cluster/distribution/eks/eksmodel/eks.go
  internal/cluster/distribution/eks/eksprovider/driver/cluster_creator.go
  internal/cluster/distribution/eks/eksprovider/driver/cluster_updater.go
  internal/cluster/distribution/eks/eksprovider/driver/cluster_updater_test.go
  internal/cluster/distribution/eks/eksprovider/workflow/amazon.go
  internal/cluster/distribution/eks/eksprovider/workflow/create_asg_activity.go
  internal/cluster/distribution/eks/eksprovider/workflow/create_infra_test.go
  internal/cluster/distribution/eks/eksprovider/workflow/save_nodepools_activity.go
  internal/cluster/distribution/eks/eksprovider/workflow/update_asg_activity.go
  internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
  internal/cluster/distribution/eks/eksworkflow/workflow_update_node_pool.go
  internal/cluster/distribution/eks/node_pool.go
  internal/cluster/distribution/eks/service.go
  src/cluster/eks.go
  src/cluster/eks_update_cluster.go
  templates/eks/amazon-eks-nodepool-cf.yaml
Labels: area/cluster, area/node-pool, cloud/aws, distribution/eks, kind/enhancement, reporter/customer

#3533 Changed default volume type gp2->gp3
  .gen/pipeline/api/openapi.yaml
  .gen/pipeline/pipeline/model_eks_node_pool_all_of.go
  .gen/pipeline/pipeline/model_eks_update_node_pool_request.go
  .gen/pipeline/pipeline/model_eks_update_node_pool_request_all_of.go
  .gen/pipeline/pipeline/model_node_pool.go
  .gen/pipeline/pipeline/model_node_pool_summary.go
  .gen/pipeline/pipeline/model_update_node_pool_request.go
  apis/pipeline/pipeline.yaml
  internal/cluster/distribution/eks/eksprovider/workflow/create_asg_activity.go
  internal/cluster/distribution/eks/eksprovider/workflow/update_asg_activity.go
  internal/cluster/distribution/eks/eksworkflow/activity_update_node_group.go
Labels: area/node-pool, cloud/aws, distribution/eks, kind/enhancement

#3531 Handle container images over 2GB size returned from `ListNodes`
  .gen/pipeline/api/openapi.yaml
  .gen/pipeline/pipeline/model_node_item_status_images.go
  apis/pipeline/pipeline.yaml
Labels: area/node-pool, kind/bug, reporter/customer

#3534 Updated Cadence local server 0.18.2->0.19.2
  docker-compose.yml
Labels: component/cadence

#3536 Fixed SyncOrgsForUser OIDC provider setting
  src/auth/authn.go
Labels: kind/bug
