Repository banzaicloud/pipeline, pull requests merged in 2021-02, with the labels that each got.

#3422 Relocated pkg/sdk/gorm->pkg/gorm
  internal/cluster/distribution/eks/eksadapter/node_pool_processor_test.go
  internal/cluster/distribution/eks/eksadapter/node_pool_store_test.go
  internal/cluster/distribution/eks/eksadapter/node_pool_validator_test.go
  internal/cluster/distribution/eks/eksprovider/workflow/list_stored_eks_clusters_activity_test.go
  pkg/gorm/test/fake_database.go
  pkg/gorm/test/fake_database_test.go
  pkg/gorm/test/test_object.go
Labels: kind/tech-debt

#3425 ci: remove unused snapshot tools
  .github/workflows/snapshot.yml
  .plzconfig
  BUILD.plz
  Makefile
  Makefile.plz
Labels: DX

#3426 Consolidated velero chart config file example to in-code default value
  config/config.yaml.dist
Labels: kind/tech-debt

#3414 Add amd64 architecture node selector to cluster autoscaler based on k8s version
  config/config.yaml.dist
  internal/cmd/config.go
  src/cluster/autoscale.go
Labels: arch/amd64

#3447 chore(Cadence): upgraded local server to 0.14.1
  docker-compose.yml
Labels: component/cadence

#3419 Refactored TokenStore garbage collection to use cron workflow
  cmd/pipeline/main.go
  cmd/worker/BUILD.plz
  cmd/worker/auth.go
  cmd/worker/main.go
  pkg/sdk/cadence/BUILD.plz
  pkg/sdk/cadence/cron.go
  pkg/sdk/cadence/cron_test.go
  src/auth/BUILD.plz
  src/auth/authn.go
  src/auth/workflow/BUILD.plz
  src/auth/workflow/garbage_collect_token_store_workflow.go
  src/auth/workflow/start_token_store_gc_workflow.go
Labels: kind/tech-debt
