Repository banzaicloud/pipeline, pull requests merged in 2023-01, with the labels that each got.

#3655 Updated packages
  .plzconfig
  config/config.yaml.dist
  docker-compose.yml
  internal/cmd/config.go
  internal/cmd/config_test.go
  internal/integratedservices/testconfig/docker-compose.yml
Labels: component/vault, build, dependencies

#3654 Added EKS 1.24, removed EKS 1.19-20 support
  docs/generate-eks-image-list.sh
  internal/cluster/distribution/eks/ekscluster/eks.go
  internal/cluster/distribution/eks/image_selector_defaults.go
Labels: cloud/aws, distribution/eks

#3657 Updated Helm chart 1.4.5->2.0.0 and Ingress template
  charts/pipeline/Chart.yaml
  charts/pipeline/templates/NOTES.txt
  charts/pipeline/templates/ingress.yaml
  charts/pipeline/values.yaml
Labels: component/helm

#3658 ci(GHA): fixed Helm version check
  .github/workflows/helm.yml
Labels: DX
